name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create script with secret
        run: |
          echo "const MY_SECRET = '${{ secrets.MY_SECRET }}';" > script.js
          echo "console.log('Secret value:', MY_SECRET);" >> script.js
          # Добавьте остальной ваш код
          cat your-main-code.js >> script.js
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
      
      - name: Debug check
        run: |
          echo "Check file content:"
          cat script.js
          echo "Secret value: ${{ secrets.MY_SECRET }}"